### ISSUE TITLE
FATA[0000] Failed to start go bin due to: ERROR: exit status 1 OUTPUT:

### ISSUE THREAD

**Issue by dongmai** [struCoder/pmgo#24]
Hi @struCoder ,

I always got this error message when trying to start an app. (the app was tusd: https://github.com/tus/tusd)

I cloned the repo to **tusd** folder, and the **main.go** file is located at **tusd/cmd/tusd/main.go**

I've tried both `pmgo start tusd/cmd/tusd/main.go TUS-API` and `pmgo start /tusd/ TUS-API` and no luck.

Can you help me to resolve this? Thanks.

**Comment by struCoder** [comment]
Hi @dongmai 
Can you run tusd by `go run cmd/tusd/main.go`? i found that it depends on `github.com/prometheus/client_golang` and `github.com/aws/aws-sdk-go/aws`

**Comment by struCoder** [comment]
@dongmai 
just sub-dir under `GOPATH/src` and do not include *.go

Have Good Time :)

**Comment by nshah14285** [comment]
I have placed the go application inside GOPATH/src/github.com/
From inside GOPATH/src I ran command pmgo start github.com/project/ app-name , it throws the error "FATA[0000] Failed to start go bin due to: ERROR: exit status 2 OUTPUT:"
Where to check the actual cause of error?
Application get started using go run command without any error.

**Comment by struCoder** [comment]
@nshah14285 
Your system is windows or based with *nix systems ?

**Comment by thetruth4u** [comment]
Hi @struCoder,
This is coming again,

`pmgo start github.com/tus/tusd/cmd/tusd TUS-API`

Do you have any idea about this?

**Comment by struCoder** [comment]
@thetruth4u 
emmmm...
That is interesting..
Do you set correct gopath?

**Comment by thetruth4u** [comment]
yes, the gopath is at **`~/go`**

**Comment by thetruth4u** [comment]
Here is my result when `go env`:
```
...
GOPATH="/home/{my_username}/go"
GOROOT="/usr/local/go"
...
```

**Comment by JeHyunwoo91** [comment]
hi @thetruth4u 
where is your source-code directory, including $GOPATH ??
i had similarly your issue , but i got solution.

if my $GOPATH, like this....
GOPATH="/home/{my_username}/go"

and my project source-code directory configured like this...
/home/{my_username}/go/github.com/abc/def/

so, i run `pmgo` command like this...
pmgo start github.com/abc/def ABC

check your project source-code directory's including $GOPATH

i hope It was a good reference to you ...
thx

**Comment by emjeard** [comment]
hi i have problem like this, this mw go env

GOARCH="amd64"
GOBIN=""
GOCACHE="/root/.cache/go-build"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/home/go/src"
GOPROXY=""
GORACE=""
GOROOT="/usr/local/go"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/linux_amd64"
GCCGO="gccgo"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build392059417=/tmp/go-build -gno-record-gcc-switches"

my source dir on home/go/src/hello
inside folder hello : main main.go

i try command like this, but still get error

root@server:/home/go/src# pmgo start /hello testpm
FATA[0000] Failed to start go bin due to: ERROR: exit status 1 OUTPUT:
root@server:/home/go/src# pmgo start hello/ testpm
FATA[0000] Failed to start go bin due to: ERROR: exit status 1 OUTPUT:

**Comment by wpbawsed** [comment]
您好～我照著相同的方式將https://github.com/tus/tusd 下載到GOPATH，並且照著專案的使用者直接開啟執行檔是可以的，但使用pmgo start github.com/tus/tusd/cmd/tusd/ tusd 一樣會發生 FATA[0000] Failed to start go bin due to: ERROR: exit status 1 OUTPUT:  系統是MAC;  GOPATH="/Users/{user_name}/go"; GOROOT="/usr/local/go"

**Comment by dicklei** [comment]
Hi @struCoder ,
I cloned the repo and
git checkout beta  and build

command-line-arguments
# command-line-arguments
./pmgo.go:103:17: too many arguments in call to cli.StartGoBin
	have (string, string, bool, []string, bool)

Can you help me to resolve this? Thanks.

**Comment by struCoder** [comment]
@dicklei Hi there
Can you show me your start command line?
